// src/components/extras/AuroraBg/AuroraBg.component.jsx
import React from 'react';
import './AuroraBg.styles.css';

const AuroraBg = () => {
	return (
		<div className='w-full h-screen blur-[150px] fixed top-0 left-0 -z-10'>
			<svg
				viewBox='0 0 200 200'
				xmlns='http://www.w3.org/2000/svg'
				className='w-[30rem] blob-1 blob absolute top-0 right-0'
			>
				<path
					fill='#0F62BA'
					d='M27.2,-51.9C33.7,-43.3,36.5,-33,42,-24C47.5,-15.1,55.7,-7.6,55.2,-0.3C54.8,7,45.7,14.1,39.1,21.2C32.6,28.2,28.5,35.3,22.4,41.7C16.3,48,8.2,53.6,-0.2,54C-8.6,54.4,-17.3,49.6,-23.5,43.4C-29.8,37.1,-33.7,29.4,-39,22C-44.2,14.5,-50.8,7.2,-57.5,-3.9C-64.2,-15,-71,-30,-64.6,-35.4C-58.2,-40.8,-38.5,-36.7,-25.5,-41.7C-12.6,-46.6,-6.3,-60.5,2,-64C10.3,-67.5,20.6,-60.5,27.2,-51.9Z'
					transform='translate(100 100)'
				/>
			</svg>
			<svg
				viewBox='0 0 200 200'
				xmlns='http://www.w3.org/2000/svg'
				className='w-[30rem] blob-2 blob absolute top-0 left-0'
			>
				<path
					fill='#BF1363'
					d='M27.2,-51.9C33.7,-43.3,36.5,-33,42,-24C47.5,-15.1,55.7,-7.6,55.2,-0.3C54.8,7,45.7,14.1,39.1,21.2C32.6,28.2,28.5,35.3,22.4,41.7C16.3,48,8.2,53.6,-0.2,54C-8.6,54.4,-17.3,49.6,-23.5,43.4C-29.8,37.1,-33.7,29.4,-39,22C-44.2,14.5,-50.8,7.2,-57.5,-3.9C-64.2,-15,-71,-30,-64.6,-35.4C-58.2,-40.8,-38.5,-36.7,-25.5,-41.7C-12.6,-46.6,-6.3,-60.5,2,-64C10.3,-67.5,20.6,-60.5,27.2,-51.9Z'
					transform='translate(100 100)'
				/>
			</svg>
		</div>
	);
};

export default AuroraBg;

// src/app/components/aurora-bg/aurora-bg.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-aurora-bg',
  templateUrl: './aurora-bg.component.html',
  styleUrls: ['./aurora-bg.component.css']
})
export class AuroraBgComponent {

}

<div
  class="w-full h-screen blur-[150px] fixed top-0 left-0 -z-10"
  id="gradient"
>
  <svg
    viewBox="0 0 200 200"
    xmlns="http://www.w3.org/2000/svg"
    class="w-[30rem] blob-1 blob absolute top-0 right-0"
  >
    <path
      fill="#0F62BA"
      d="M27.2,-51.9C33.7,-43.3,36.5,-33,42,-24C47.5,-15.1,55.7,-7.6,55.2,-0.3C54.8,7,45.7,14.1,39.1,21.2C32.6,28.2,28.5,35.3,22.4,41.7C16.3,48,8.2,53.6,-0.2,54C-8.6,54.4,-17.3,49.6,-23.5,43.4C-29.8,37.1,-33.7,29.4,-39,22C-44.2,14.5,-50.8,7.2,-57.5,-3.9C-64.2,-15,-71,-30,-64.6,-35.4C-58.2,-40.8,-38.5,-36.7,-25.5,-41.7C-12.6,-46.6,-6.3,-60.5,2,-64C10.3,-67.5,20.6,-60.5,27.2,-51.9Z"
      transform="translate(100 100)"
    />
  </svg>
  <svg
    viewBox="0 0 200 200"
    xmlns="http://www.w3.org/2000/svg"
    class="w-[30rem] blob-2 blob absolute top-0 left-0"
  >
    <path
      fill="#BF1363"
      d="M27.2,-51.9C33.7,-43.3,36.5,-33,42,-24C47.5,-15.1,55.7,-7.6,55.2,-0.3C54.8,7,45.7,14.1,39.1,21.2C32.6,28.2,28.5,35.3,22.4,41.7C16.3,48,8.2,53.6,-0.2,54C-8.6,54.4,-17.3,49.6,-23.5,43.4C-29.8,37.1,-33.7,29.4,-39,22C-44.2,14.5,-50.8,7.2,-57.5,-3.9C-64.2,-15,-71,-30,-64.6,-35.4C-58.2,-40.8,-38.5,-36.7,-25.5,-41.7C-12.6,-46.6,-6.3,-60.5,2,-64C10.3,-67.5,20.6,-60.5,27.2,-51.9Z"
      transform="translate(100 100)"
    />
  </svg>
</div>
